# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAdministrador.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanaEditarCorreo import Ui_ventanaEditarCorreo
import requests
import json


class Ui_VentanaAdministrador(object):
    def setupUi(self, VentanaAdministrador):
        VentanaAdministrador.setObjectName("VentanaAdministrador")
        VentanaAdministrador.resize(400, 272)
        self.botonBorrar = QtWidgets.QPushButton(VentanaAdministrador)
        self.botonBorrar.setGeometry(QtCore.QRect(300, 50, 75, 23))
        self.botonBorrar.setObjectName("botonBorrar")
        self.botonActualizar = QtWidgets.QPushButton(VentanaAdministrador)
        self.botonActualizar.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.botonActualizar.setObjectName("botonActualizar")
        self.label = QtWidgets.QLabel(VentanaAdministrador)
        self.label.setGeometry(QtCore.QRect(20, 20, 251, 21))
        self.label.setObjectName("label")
        self.cajaGanadores = QtWidgets.QListWidget(VentanaAdministrador)
        self.cajaGanadores.setGeometry(QtCore.QRect(20, 50, 256, 192))
        self.cajaGanadores.setObjectName("cajaGanadores")
        #CONFIGURACIÓN DEL CONTENIDO DE LA CAJA DE GANADORES
        with open("correos.txt", "r") as f:
            self.correos = json.load(f)
        for correo in self.correos:
            self.cajaGanadores.addItem(correo)
        #BOTONES
        self.botonBorrar.clicked.connect(self.borrarCorreo)
        self.botonActualizar.clicked.connect(self.abrirVentanaEditarCorreo)

        self.retranslateUi(VentanaAdministrador)
        QtCore.QMetaObject.connectSlotsByName(VentanaAdministrador)

    def retranslateUi(self, VentanaAdministrador):
        _translate = QtCore.QCoreApplication.translate
        VentanaAdministrador.setWindowTitle(_translate("VentanaAdministrador", "Spell Guesser 0.3 - Administrador"))
        self.botonBorrar.setText(_translate("VentanaAdministrador", "Borrar"))
        self.botonActualizar.setText(_translate("VentanaAdministrador", "Actualizar"))
        self.label.setText(_translate("VentanaAdministrador", "<html><head/><body><p align=\"center\">Ganadores</p></body></html>"))
    
    def borrarCorreo(self):
        try:
            self.itemBorrar = self.cajaGanadores.currentItem()
            self.valorItemBorrar = self.itemBorrar.text()
            self.idItemBorrar = self.correos[self.valorItemBorrar]
            self.correoBorrado = requests.post("https://pastebin.com/api/api_post.php", {"api_dev_key" : "7sx-6yY4AklaGZyTeA0Njr9v9-DkQD8m", "api_user_key": "afaacc8ab76221d203329da5c3d257d6", "api_option" : "delete", "api_paste_key": self.idItemBorrar})
            self.index = self.cajaGanadores.indexFromItem(self.itemBorrar)
            self.posicionItemBorrar = self.index.row()
            self.item = self.cajaGanadores.takeItem(self.posicionItemBorrar)
            del self.item
            del self.correos[self.valorItemBorrar]
            with open('correos.txt', 'w') as f:
                json.dump(self.correos, f)
        except:
            pass
    
    def abrirVentanaEditarCorreo(self):
        try:
            self.itemActualizar = self.cajaGanadores.currentItem()
            self.valorItemActualizar = self.itemActualizar.text()
            self.idItemActualizar = self.correos[self.valorItemActualizar]
            self.correoActualizar = {self.valorItemActualizar : self.idItemActualizar}
            with open("correo.txt", "w") as f:
                json.dump(self.correoActualizar, f)
            self.ventana = QtWidgets.QMainWindow()
            self.ui = Ui_ventanaEditarCorreo()
            self.ui.setupUi(self.ventana)
            self.ventana.show()
        except:
            pass
