# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaEditarCorreo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import json


class Ui_ventanaEditarCorreo(object):
    def setupUi(self, ventanaEditarCorreo):
        ventanaEditarCorreo.setObjectName("ventanaEditarCorreo")
        ventanaEditarCorreo.resize(400, 109)
        self.label = QtWidgets.QLabel(ventanaEditarCorreo)
        self.label.setGeometry(QtCore.QRect(0, 10, 401, 20))
        self.label.setObjectName("label")
        self.cajaTextoEditarCorreo = QtWidgets.QLineEdit(ventanaEditarCorreo)
        self.cajaTextoEditarCorreo.setGeometry(QtCore.QRect(90, 40, 211, 20))
        self.cajaTextoEditarCorreo.setObjectName("cajaTextoEditarCorreo")
        self.botonActualizarCorreo = QtWidgets.QPushButton(ventanaEditarCorreo)
        self.botonActualizarCorreo.setGeometry(QtCore.QRect(160, 70, 75, 23))
        self.botonActualizarCorreo.setObjectName("botonActualizarCorreo")
        #BOOLEANO DE CORREO ENVIADO
        self.correoEnviado = False
        #OBTIENE LOS CORREOS TOTALES
        with open("correos.txt", "r") as f:
            self.correos = json.load(f)
        #OBTIENE EL CORREO QUE ACTUALIZARÁ
        with open("correo.txt", "r") as f:
            self.correo = json.load(f)
        self.ValorCorreo = list(self.correo.keys())
        self.idCorreo = list(self.correo.values())
        #BOTONES
        self.botonActualizarCorreo.clicked.connect(self.enviarNuevoCorreo)

        self.retranslateUi(ventanaEditarCorreo)
        QtCore.QMetaObject.connectSlotsByName(ventanaEditarCorreo)

    def retranslateUi(self, ventanaEditarCorreo):
        _translate = QtCore.QCoreApplication.translate
        ventanaEditarCorreo.setWindowTitle(_translate("ventanaEditarCorreo", "Spell Guesser 0.3"))
        self.label.setText(_translate("ventanaEditarCorreo", "<html><head/><body><p align=\"center\">Ingresa un nuevo valor</p></body></html>"))
        self.botonActualizarCorreo.setText(_translate("ventanaEditarCorreo", "Actualizar"))
    
    def enviarNuevoCorreo(self):
        if len(self.cajaTextoEditarCorreo.text()) > 10 and self.correoEnviado == False:
            #ELIMINA EL PASTE SELECCIONADO
            self.correoBorrado = requests.post("https://pastebin.com/api/api_post.php", {"api_dev_key" : "7sx-6yY4AklaGZyTeA0Njr9v9-DkQD8m", "api_user_key": "afaacc8ab76221d203329da5c3d257d6", "api_option" : "delete", "api_paste_key": self.idCorreo[0]})
            del self.correos[self.ValorCorreo[0]]
            with open('correos.txt', 'w') as f:
                json.dump(self.correos, f)
            #CREA EL NUEVO PASTE CON EL CORREO ACTUALIZADO
            self.correoPublicado = requests.put("https://pastebin.com/api/api_post.php", {"api_dev_key" : "7sx-6yY4AklaGZyTeA0Njr9v9-DkQD8m", "api_user_key": "afaacc8ab76221d203329da5c3d257d6", "api_option" : "paste", "api_paste_code": self.cajaTextoEditarCorreo.text(), "api_paste_private" : "0" })
            self.correos[self.cajaTextoEditarCorreo.text()] = self.correoPublicado.text[21:]
            with open('correos.txt', 'w') as f:
                json.dump(self.correos, f)
            print("Enviado")
            self.correoEnviado = True
